
real	0m36.583s
user	0m31.047s
sys	0m2.142s

real	1m34.345s
user	1m30.245s
sys	0m1.875s

real	0m43.903s
user	0m39.644s
sys	0m1.686s

real	2m44.750s
user	2m12.211s
sys	0m18.750s

real	0m40.834s
user	0m37.637s
sys	0m1.452s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 187, in <module>
    Cl = pk.load(f)
EOFError: Ran out of input

real	0m2.081s
user	0m1.353s
sys	0m0.203s

real	0m47.270s
user	0m41.183s
sys	0m4.062s

real	1m56.545s
user	1m51.699s
sys	0m2.063s

real	0m41.511s
user	0m38.453s
sys	0m1.369s

real	2m12.024s
user	1m59.519s
sys	0m8.889s

real	1m10.067s
user	1m0.085s
sys	0m6.972s

real	2m0.328s
user	1m55.195s
sys	0m2.203s

real	0m55.909s
user	0m47.264s
sys	0m6.323s

real	2m8.190s
user	2m3.164s
sys	0m2.156s

real	0m49.097s
user	0m45.755s
sys	0m1.528s

real	2m20.942s
user	2m5.306s
sys	0m11.700s

real	0m52.194s
user	0m45.611s
sys	0m4.582s

real	1m37.474s
user	1m31.377s
sys	0m3.493s

real	0m38.812s
user	0m32.975s
sys	0m4.011s

real	1m38.755s
user	1m34.752s
sys	0m1.839s
