
real	0m47.795s
user	0m40.005s
sys	0m3.420s

real	1m56.261s
user	1m51.706s
sys	0m2.071s

real	1m8.852s
user	1m3.729s
sys	0m1.853s

real	2m27.191s
user	2m14.994s
sys	0m8.360s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 187, in <module>
    Cl = pk.load(f)
EOFError: Ran out of input

real	0m2.023s
user	0m1.346s
sys	0m0.204s

real	2m8.977s
user	2m4.253s
sys	0m2.035s

real	0m57.067s
user	0m49.599s
sys	0m5.158s

real	2m3.663s
user	1m58.845s
sys	0m2.075s

real	1m18.848s
user	1m11.634s
sys	0m4.733s

real	2m6.663s
user	2m1.793s
sys	0m2.074s

real	0m59.525s
user	0m56.413s
sys	0m1.388s

real	2m15.444s
user	2m10.473s
sys	0m2.026s

real	0m54.720s
user	0m45.286s
sys	0m6.549s

real	1m54.376s
user	1m49.966s
sys	0m1.923s

real	1m28.210s
user	1m18.971s
sys	0m6.733s

real	2m55.607s
user	2m40.340s
sys	0m11.389s

real	1m26.962s
user	1m16.926s
sys	0m7.411s

real	2m53.604s
user	2m37.809s
sys	0m11.576s

real	0m48.112s
user	0m43.131s
sys	0m3.277s

real	1m38.189s
user	1m34.565s
sys	0m1.760s
