
real	0m57.581s
user	0m49.873s
sys	0m3.640s

real	3m39.190s
user	2m29.144s
sys	0m38.757s

real	0m57.940s
user	0m50.355s
sys	0m5.035s

real	2m1.688s
user	1m56.752s
sys	0m2.096s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 184, in <module>
    Cp = pk.load(f)
EOFError: Ran out of input

real	0m2.022s
user	0m1.348s
sys	0m0.194s

real	1m55.668s
user	1m51.165s
sys	0m1.874s

real	1m9.408s
user	1m1.903s
sys	0m5.264s

real	2m4.373s
user	1m59.708s
sys	0m1.929s

real	1m1.871s
user	0m53.275s
sys	0m6.195s

real	3m1.929s
user	2m37.915s
sys	0m18.313s

real	0m41.433s
user	0m38.359s
sys	0m1.390s

real	2m1.047s
user	1m56.286s
sys	0m1.964s

real	0m47.099s
user	0m43.998s
sys	0m1.453s

real	2m28.210s
user	2m8.383s
sys	0m15.421s

real	0m37.703s
user	0m34.415s
sys	0m1.508s

real	1m45.270s
user	1m40.716s
sys	0m2.306s

real	0m35.665s
user	0m32.891s
sys	0m1.383s

real	1m47.436s
user	1m43.353s
sys	0m1.862s

real	0m36.258s
user	0m33.623s
sys	0m1.267s

real	1m33.618s
user	1m24.983s
sys	0m6.081s
